### ISSUE TITLE
Add test project structure

### ISSUE THREAD

**Issue by marqueslu** [marqueslu/little-cash#2]
# Description
Deve ser feito todo o setup necessário para rodarmos testes de integração, unitário e funcional.
Também deve ser incluído as libs necessárias.

## To-Dos:
- [ ] Criar o projeto de unit test
- [ ] Criar o projeto de integration test
- [ ] Criar o projeto de functional test
- [ ] Incluir as libs Moq, Bogus e FluentAssertions
