### ISSUE TITLE
Add new Api project

### ISSUE THREAD

**Issue by marqueslu** [marqueslu/little-cash#3]
# Description
Deve ser criado uma estrutura inicial de api, diferente da que já temos hoje no projeto.
A que temos hoje, é utilizando as minimals API, porém, como estamos espelhando o projeto da RO, acaba sendo melhor termos uma estrutura de api similar.

## To-dos:
- [ ] Criar uma branch entitulada `feat/example-minimal-api` para mantermos um histórico da minimal api e utilizarmos de exemplo
- [ ] Criar o novo projeto de api migrando algumas configurações da `Program.cs` para a nova api
- [ ] Remover o antigo projeto de api
